### PR TITLE
node version 16 as prerequisite

### PR DESCRIPTION
**Pull request by Maharacha**
Should this be 16 since the tests uses 16? Maybe even `==` instead of `>` ?

### CODE REVIEW

**Comment by Ank4n** [comment]
Or we can add build workflow with node 14 and 15 as well?

**Comment by Maharacha** [comment]
> Or we can add build workflow with node 14 and 15 as well?

That sounds like a good idea if it works, as long as the tests reflects the prerequisites.

**Comment by rvalle** [comment]
@Maharacha @Ank4n I don't think the node 16 prerequisite is an issue.
Current active versions are 16 and 18.
Working with version 14 gives a logs of warnings of out-dated and unmaintained libraries.

I think supporting 14 would be relevant if we were implementing a library likely to be integrated in other projects, or something like that.

I think I would go with 16 or more, and if you want to test additional ones, test the 18.

**Review by Ank4n — APPROVED** [review]
I will merge this!

**Pull request merged**
